### ISSUE TITLE
Visualization "The Transition pathway" > "Production", error in "transport"

### ISSUE THREAD

**Issue by fradmm** [ZEN-universe/ZEN-explorer#13]
in "The Transition pathway" > "Production" > 15_multiple_output_carriers_conversion_tech > transport > natural_gas 
it says "No data with this selection" while there should be the total natural gas transport over the natural_gas_pipeline to be visualized.

Also, in "Data selection" (same case), if selecting "technology", it shows natural_gas_pipeline -correct, but not shown-, and also natural_gas_storage -incorrect, because is a storage technology-. 

I think this error is common to all the Production>transport cases. For reference, see slide 15 in the visualization presentation.

**Comment by vinzenz-muser** [comment]
Done
