### ISSUE TITLE
[Producion] Electricity production not shown

### ISSUE THREAD

**Issue by fradmm** [ZEN-universe/ZEN-explorer#16]
In The Transition Pathway > Production > 7_multiple_time_steps_per_year > conversion > output > Carrier: electricity 
it says "No data with this selection".

However, there are data to show, since there are "photovoltaics" that have electricity as output.
This dataframe is obtained by prompting `.get_total("flow_conversion_output")`:
![image](https://github.com/user-attachments/assets/2bb0b23e-1be4-4189-9a60-f9ac5348ade7)

The visualization works for carrier: heat. It correctly shows heat produced by the natural_gas_boiler. 
It does not work for carrier: electricity.

**Comment by vinzenz-muser** [comment]
Should be fixed now.
