### ISSUE TITLE
[Energy balance] Use Step area plot

### ISSUE THREAD

**Issue by fradmm** [ZEN-universe/ZEN-explorer#17]
In The Energy Balance, the stacked area plots show some graphical glitches, especially on the transients along the timesteps. 
A quick example in `15_multiple_output_carriers_conversion_tech` > year: 2024 > Node: CH > Carrier: natural_gas > time zoom, approximately [ 11250: 11290 ]. Highlighting with red the glitches, the following plots are the same configuration, activating/deactivating various components:
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/b771aa00-e7c3-4157-966b-63de9b457ea1">
<img width="999" alt="image" src="https://github.com/user-attachments/assets/43441c3e-e8c0-4b0d-8173-d163a212e167">
![image](https://github.com/user-attachments/assets/05d20edd-c87c-41d5-8c65-9fb39176ac6d)
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/74f19569-de8d-4d56-925e-2b11b81fb734">

A way to fix this is to keep constant values between time-steps, using step visualization. Here is an example to explain it better (also saved in the shared ppt):
![image](https://github.com/user-attachments/assets/d7618009-a97d-4fb4-9df1-07cd38fc6375)

**Comment by jacob-mannhardt** [comment]
I increased the prio from low to high as this behavior of the overlapping colors is doesn't make sense

**Comment by vinzenz-muser** [comment]
I changed the opacity of the plots to 1 and added the steps. I think it should be fine now, but we can have a look at it together.
