### ISSUE TITLE
[General organization] Nested result folders

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#18]
So far, we can access all results that are in the first level of a folder, e.g.,:
```
outputs
|- result_1
|- result_2
`- result_3
```
However, it might be desirable to organize the results in folders, e.g., to collect all results of individual studies, e.g.,:
```
outputs
|- study_1
|   |- result_1_1
|   `- result_1_1
|- study_2
|   |- result_2_1
|   `- result_3_1
`- result_3
```
Is that possible? Would also be nice for the offline version.

**Comment by vinzenz-muser** [comment]
Is implemented in next version.
