### ISSUE TITLE
[general] hardcoded that it is looking for the /outputs folder

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#21]
If we accidentally start the visualization directly from the /outputs folder, it throws an error that it doesn't find /outputs. Could we allow starting it from /outputs as well, i.e., first checking if /outputs exists and then if that fails check if there are any ZEN-garden solutions in the current folder?

**Comment by vinzenz-muser** [comment]
How about we take cwd as default instead of ./outputs? I would not add too much logic into the solution-finding...

**Comment by jacob-mannhardt** [comment]
I like it that we can run a model and then type
```
python -m zen_garden.visualization
```
and the new result directly shows up, without the need of using `cd outputs`

**Comment by vinzenz-muser** [comment]
I really would roule against this since it contains so many edge cases that have to be considered and will probably become messy. I would stick to the current solution and if you want to run it in the current folder you can run `python -m zen_garden.visualization .`

**Comment by vinzenz-muser** [comment]
As discussed, I close this.
