### ISSUE TITLE
[general] stop local server when closing the window?

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#22]

**Comment by vinzenz-muser** [comment]
This is not possible since there is no way for the server to know if you have an open browser (or tab) or not.

**Comment by jacob-mannhardt** [comment]
What is then the best way to stop the server? ctrl+c? @vinzenz-muser

**Comment by vinzenz-muser** [comment]
@jacob-mannhardt yes, ctrl+c is the recommended way.

**Comment by jacob-mannhardt** [comment]
@vinzenz-muser okay thanks! Could you please add that to the documentation? Many thanks
