### ISSUE TITLE
[probably general on local server] error when switching from e.g. capacity to energy_balance

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#23]
It tries to go from `http://localhost:8000/explorer/transition/capacity/` to `http://localhost:8000/explorer/transition/capacity/energy_balance`, which doesn't exist

so the error below occurs

![image](https://github.com/user-attachments/assets/11ddfd9c-d5fe-4f18-98e5-27c153111d6b)

**Comment by vinzenz-muser** [comment]
Is fixed in version 0.0.7, you can upgrade with `pip install zen_temple==0.0.7`
