### ISSUE TITLE
[Energy Balance] caching old data when overwriting solution

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#25]
After overwriting the solution, the energy balance still shows the cached data from previous runs.

Proposed fix: we check the creation/changing date of the scenarios.json file (or whatever file is used to identify a ZEN-garden solution on the platform). If it didn't change we can use the cached solution, otherwise calculate again

**Comment by vinzenz-muser** [comment]
This is fixed in version 0.0.8.
