### ISSUE TITLE
[general] right click and open in new tab doesn't work

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#26]
when coming from the transition pathway, clicking on the energy balance the correct link is [https://zen-land.ethz.ch/explorer/energy_balance/](https://zen-land.ethz.ch/explorer/energy_balance/). When right clicking and "open in new tab" the link is wrong [https://zen-land.ethz.ch/energy_balance/](https://zen-land.ethz.ch/energy_balance/)

**Comment by vinzenz-muser** [comment]
Can you verify that this works on [https://www.zen-garden.ethz.ch/explorer/energy_balance/](https://www.zen-garden.ethz.ch/explorer/energy_balance/)? zen-land.ethz.ch is the old hosting and will not be updated (because the deployment works differently there)

**Comment by jacob-mannhardt** [comment]
yep, works!
