### ISSUE TITLE
[Production]

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#27]
no values shown in 
2_add_photovoltaics -> Production -> conversion -> output -> electricity
should show photovoltaics

**Comment by jacob-mannhardt** [comment]
hypothesis: photovoltaics filtered out because it doesn't have an input carrier

**Comment by fradmm** [comment]
For further details, see this issue: https://github.com/ZEN-universe/ZEN-explorer/issues/16

**Comment by jacob-mannhardt** [comment]
closed as duplicate
