### ISSUE TITLE
[Emissions] Annual/Cumulative cannot be changed after selecting subdivision

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#31]
After selecting subdivision, the buttons for annual or cumulative are gone.
![image](https://github.com/user-attachments/assets/b277acf9-360f-490f-a27e-0bf101372673)

**Comment by vinzenz-muser** [comment]
I thought this was supposed to be like this? If Subdivision is off, we show carbon_emissions_annual or carbon_emissions_cumulative, if it is on, we show carbon_emissions_technology and
carbon_emissions_carrier

**Comment by jacob-mannhardt** [comment]
ok I agree, but the y-label is different depending on what you selected before

**Comment by vinzenz-muser** [comment]
I changed the y label to "Emissions", let me know if you want something else. (Once the Units are correct I think this makes sense)
