### ISSUE TITLE
[Cost] Variables renamed

### ISSUE THREAD

**Issue by fradmm** [ZEN-universe/ZEN-explorer#36]
The following cost variables have been renamed in ZEN-garden. Please update the temple for a correct visualization

| Variable old name | Variable new name |
|-----|---------|
| `opex_yearly` | `cost_opex_yearly` |
| `cost_opex_total` | `cost_opex_yearly_total` |
| `cost_opex` | `cost_opex_variable` |
| `capex_yearly` | `cost_capex_yearly` |
| `cost_capex_total` | `cost_capex_yearly_total` |
| `cost_capex` | `cost_capex_overnight` |

**Comment by vinzenz-muser** [comment]
Fixed in next release.
