### ISSUE TITLE
[Energy balance] Multiple Export labels

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#39]
Energy balance shows multiple export labels. Unclear what that is.

![image](https://github.com/user-attachments/assets/64f824dc-19d4-4f27-b0b1-5c4566a8b42b)

**Comment by vinzenz-muser** [comment]
Which solution and carrier is this?

**Comment by jacob-mannhardt** [comment]
PI and electricity, DE

**Comment by vinzenz-muser** [comment]
Fixed in next version.
