### ISSUE TITLE
[general] finding solutions when specifying the folder path

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#41]
I have the following setup:
```
result_path
|- solution_1
|- solution_2
`- solution_3
```
If I direct the visualization to
`<parent_path>/result_path`, the solution folders are shown as `/solution_1`, `/solution_2`, and `/solution_3`. Selecting one solution and any plot then yields `GET /solutions/get_detail//solution_1 HTTP/1.1" 404 Not Found`. Note the double `//`. We should remove trailing `/`.

**Comment by fradmm** [comment]
@vinzenz-muser please also check slide "Nested folders exploration" on the shared "Presentation ZEN garden visualization.pptx"

**Comment by vinzenz-muser** [comment]
Done in new release.
