### ISSUE TITLE
[Production] units are wrong

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#42]
The units are wrong in the Production plots. I assume that the first value of the unit data frame is taken without regard for the energy carrier (e.g., carbon should not have the unit gigawatt). It is correct for the energy balance. 

![image](https://github.com/user-attachments/assets/785d7f3e-f17c-4191-a227-e246307a12a5)

**Comment by vinzenz-muser** [comment]
Fixed in next release.
