### ISSUE TITLE
[Energy Balance] Shed demand missing?

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#45]
The energy balance doesn't hold (operation_scenarios -> operation -> 2022, AT, heat). I suspect it is because of shed demand missing. Is that correct?
![image](https://github.com/user-attachments/assets/babb07da-87a7-4e5f-ba09-f466cb1ef500)

**Comment by jacob-mannhardt** [comment]
this is not a cost plot

**Comment by vinzenz-muser** [comment]
Oh yes, sorry. Will be fixed in next version.
