### ISSUE TITLE
[get_variable_name] for all variable names, not just costs

### ISSUE THREAD

**Issue by jacob-mannhardt** [ZEN-universe/ZEN-explorer#50]
We implemented get_variable_name to allow for a flexible updating of variable and parameter names. It is currently only applied to cost terms. If we change any other name of any other parameter or variable, it doesn't work anymore

**Comment by vinzenz-muser** [comment]
This should work for every variable, if it is not configured with an overwritten name, the same name that you pass as argument is returned, so it works with any string.
